### ISSUE TITLE
'ascii' codec can't decode byte error when accessing admin interface

### ISSUE THREAD

**Issue by rzinurov** [django-notifications/django-notifications#63]
Hi guys,
First of all I would like to say thank you for this app. It's really easy to setup and use it and it brings a lot of great functionality. It works great but when I try to open notifications list in Django admin interface I'm getting this error:
```
'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128). You passed in <Notification: [Bad Unicode data]> (<class 'notifications.models.Notification'>)
```
I think this happens because I have cyrillic characters in notification `target` field. This issue is also reproducible with `django-activity-stream`. Please let me know if there is any temporary workaround. I'm using `django-notifications-hq==0.6.2`.

**Comment by yangyubo** [comment]
@rzinurov This should have already fixed in version 0.7.0, upgrade to latest release and give it a try.

**Comment by rzinurov** [comment]
Upgrading to version 0.7.0 has fixed the issue, thanks. I see that the issue is still exist in `django-activity-stream v0.5.1` so could you please describe how you fixed it in your app?

**Comment by yangyubo** [comment]
See here: #4

**Comment by rzinurov** [comment]
Thanks a lot!
